###endpoint para obtener datos generales de los nodos 
GET 
Content-Type:application/json
Authorization: 

###Endpoint para obtener datos del estandar usado para monitoreo de vibraciones
GET 

###Endpoint para obtener datos de eventos  de espectro segun trigger

GET 

###Endpoint para obtener datos de geofonos por evento

GET 

###Enpo

GET 
Content-Type:application/json
Authorization: Bearer 
